# Generated by Django 5.1.5 on 2025-04-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='', related_name='fituser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='fituser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='', related_name='fituser_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
