# Generated by Django 5.1.5 on 2025-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fituser_options_alter_fituser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fituser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
