# Generated by Django 5.1.5 on 2025-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fituser_first_name_fituser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='calBurnedHistory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fituser',
            name='sleepHistory',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
